Home work8
LinarKhmblov/AutoTest_Tensor pull request #10
Opened 2023-06-01 15:16 UTC by LinarKhmblov

2023-06-01 18:03 UTC, vlad-vladimirovich requested changes

2023-06-01 18:03 UTC, vlad-vladimirovich commented on HomeWork_8/task1.py
> +        if len(our_tuple) == 2:
в блоке try не надо писать if else и тд. этот блок только для выполнения кода. а все возможные исключения надо отлавливать после его выполнения. в твоем случае в try должна выполняться только конкатенация твоего кортежа

2023-06-01 18:03 UTC, vlad-vladimirovich commented on HomeWork_8/task2.py
> +class Trigon():
нет доки к классу

2023-06-01 18:03 UTC, vlad-vladimirovich commented on HomeWork_8/task2.py
> +        n = len(args)
в таких моментах лучше не засовывать len(args) в переменную. обратись к len прямо в коде

2023-06-01 18:03 UTC, vlad-vladimirovich commented on HomeWork_8/task2.py
> +        self.sides = sides
это тут явно лишнее

2023-06-01 18:03 UTC, vlad-vladimirovich commented on HomeWork_8/task2.py
> +        sides = []
ты объявил пустой список и в цикле добавляешь в него значения. а потом обращаешься к нему в 33 строке. зачем? проще же просто разово в 33 обратиться к твоим аргсам

2023-06-01 18:03 UTC, vlad-vladimirovich commented on HomeWork_8/task2.py
> +            if type(i) not in (int, float):
для проверки типов данных правильно использовать функцию isinstance(). type() немного не о том

2023-06-01 18:03 UTC, vlad-vladimirovich commented on HomeWork_8/task3.py
> +        return summ
тут вооще все красиво написал. почему не сделал так же в других заданиях...

2023-06-02 06:05 UTC, LinarKhmblov commented on HomeWork_8/task3.py
> +        return summ
с этим кодом я долго возился, из-за того что последняя проверка всё никак не проходила

2023-06-02 12:47 UTC, vlad-vladimirovich approved these changes

2023-06-05 05:16 UTC, merged